/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#060e20",
        "on-primary-container": "#000000",
        "on-primary": "#080079",
        "on-error-container": "#ff97a3",
        "on-secondary": "#4e03b8",
        "tertiary-fixed": "#fea619",
        "tertiary-dim": "#e79400",
        "surface-variant": "#142449",
        "on-secondary-fixed": "#4d00b7",
        "tertiary-container": "#fea619",
        "error-container": "#8a1632",
        "secondary-fixed-dim": "#ddcdff",
        "outline-variant": "#38476d",
        "secondary-dim": "#8455ef",
        "surface-container-high": "#101e3e",
        "background": "#060e20",
        "on-primary-fixed-variant": "#2d2cbd",
        "secondary-container": "#2f0076",
        "on-background": "#dee5ff",
        "outline": "#65759e",
        "surface-bright": "#172b54",
        "error-dim": "#c8475d",
        "primary-dim": "#6063ee",
        "surface-container-highest": "#142449",
        "primary-container": "#7073ff",
        "inverse-surface": "#faf8ff",
        "on-tertiary-fixed": "#311c00",
        "surface": "#060e20",
        "on-surface-variant": "#9baad6",
        "inverse-on-surface": "#4d556b",
        "on-tertiary-container": "#4f3000",
        "error": "#fd6f85",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#babbff",
        "primary-fixed-dim": "#aaacff",
        "on-surface": "#dee5ff",
        "surface-container-low": "#081329",
        "inverse-primary": "#494bd7",
        "secondary-fixed": "#e9ddff",
        "surface-container": "#0c1934",
        "on-tertiary": "#5c3800",
        "on-tertiary-fixed-variant": "#5b3800",
        "surface-tint": "#9093ff",
        "tertiary-fixed-dim": "#ee9800",
        "primary": "#9093ff",
        "secondary": "#d0bcff",
        "on-secondary-container": "#b192ff",
        "on-error": "#490013",
        "on-primary-fixed": "#0c0090",
        "tertiary": "#ffb95f",
        "on-secondary-fixed-variant": "#6a37d4",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
